### PR TITLE
Some small Bugfixes:

### PR DESCRIPTION
**Pull request by Blog404DE**
- rssi generation failed on some wifi dongles (0 / -256)
- UTF-8 encoded SSID could lead to crash
- Set Scrapy Log-Level to "Error"

### CODE REVIEW

**Comment by danielgohlke** [comment]
thanks for the fix

**Comment by Blog404DE** [comment]
np :-) 

I’m currently working on a second patch, because there are still some problem with UTF-8 and Python2. The script still could crash, if the SSID couldn’t decode the utf-8 string (and i had some really weird SSIDs like "��@-5�\r\u0000\u0000\u0000�\u0000-\u0010��\u0003-\u0005\u0000}p\u0003“).

My first solution was to make decode() more fault-tolerant and let it replace unknown UTF-8 chars (or let them ignore it). But there where still crashes with some SSID. 

The only solution i’ve found was to make the script Python3-compatible. I have been testing the Python3 version for 3 days now and so far there have been no problems/crashes. The switch to Python3 also has another advantage - on the RaspberryPi the system load was significantly reduced by the script.

If it stays stable, I'll deploy the patch, too.

**Comment by danielgohlke** [comment]
yes i also have some "UnicodeDecodeError: 'utf8' codec can't decode byte 0xc6 in position 1: invalid continuation byte" from time to time. do you deploy it in your fork or as pull request here ?

**Comment by Blog404DE** [comment]
I had the changes running about 1 week without a crash. The changes should be appended to this pull request.

**Changelog:** 
- "Invalid" UTF-8 SSIDs are now simply replaced (if possible) with valid characters.
- A second change is to create a PID file so systemd is able to detect a crash of the daemon (-> readme.md).

**Important:** the new version uses Python3 now.. Therefore the required libraries (netaddr , scapy) have to be reinstalled using _pip3_ or the source code (_python3 setup.py install_).

**Comment by danielgohlke** [comment]
found also a other solution for python2 but it takes a huge load of cpu
replace 
`sensor_data['ssid'] = packet.info.decode("utf-8")
`with 
`sensor_data['ssid'] = unicode(packet.info, "utf-8")
`

**Comment by Blog404DE** [comment]
> found also a other solution for python2 but it takes a huge load of cpu
> replace
> `sensor_data['ssid'] = packet.info.decode("utf-8") `with
> `sensor_data['ssid'] = unicode(packet.info, "utf-8")`

i’ve tried it, too and got the same result - the cpu load and the decoding-time was 👎 
I then did a small benchmark with python2 and python3. The result of the small benchmark was the reason for my switch to python3.

**Comment by danielgohlke** [comment]
yep right same issues again, i will test now your python3 modification
there is no setup.py

**Comment by danielgohlke** [comment]
Hello again @Blog404DE,

unfortunatly i got a error today:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 324, in __getattr__
    fld, v = self.getfield_and_val(attr)
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 324, in __getattr__
    fld, v = self.getfield_and_val(attr)
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/github/probemon404/probemon.py", line 197, in <module>
    main()
  File "/home/pi/github/probemon404/probemon.py", line 189, in main
    sniff(iface=args.interface, prn=built_packet_cb, store=0, monitor=True)
  File "/usr/local/lib/python3.5/dist-packages/scapy/sendrecv.py", line 886, in sniff
    r = prn(p)
  File "/home/pi/github/probemon404/probemon.py", line 72, in packet_callback
    if packet.type != 0 or packet.subtype != 0x04:
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 326, in __getattr__
    return self.payload.__getattr__(attr)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 326, in __getattr__
    return self.payload.__getattr__(attr)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 324, in __getattr__
    fld, v = self.getfield_and_val(attr)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 1427, in getfield_and_val
    raise AttributeError(attr)
AttributeError: type

```

what do you think about this change
```
 71         # if neither match we are done here
 72         if packet.type is not None:
 73             if packet.type != 0 or packet.subtype != 0x04:
 74                 return
 75         else:
 76             return
```

**Comment by Blog404DE** [comment]
Hello Daniel,

> unfortunatly i got a error today:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 324, in __getattr__
>     fld, v = self.getfield_and_val(attr)
> TypeError: 'NoneType' object is not iterable

ok, interesseting - it seems, this error depends on your Wifi-Chipset/Firmware, because i’ve didn’t hat this messages (Ralink RT5370). But that’s no problem - your fix should avoid packet-types with „None“. 

> what do you think about this change
> 
> ```python
>  71         # if neither match we are done here
>  72         if packet.type is not None:
>  73             if packet.type != 0 or packet.subtype != 0x04:
>  74                 return
>  75         else:
>  76             return
> ```

good idea - but you could write it a bit smaller:

```python
        # we are looking for management frames with a probe subtype
        # if neither match we are done here
        if packet.type != 0 or packet.subtype != 0x04 or packet.type is None:
            return
```

I’ve just updated my pull request with this bugfix  #(eb277dd)

**Comment by danielgohlke** [comment]
@klein0r could you please react to this pull request. the improvements of @Blog404DE are necessary to run your modified script in a proper way

**Comment by klein0r** [comment]
Thanks a lot - merged it 👍

**Pull request merged**
